version: "3"

services:
  web-article:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-article
    restart: on-failure
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - 8000:80
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=web_article
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=172.25.0.3
    volumes:
      - db:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch,elasticsearchtest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=elasticsearch,elasticsearchtest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  elasticsearchtest:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearchtest
    environment:
      - node.name=elasticsearchtest
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch,elasticsearchtest
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=elasticsearch,elasticsearchtest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdatatest:/usr/share/elasticsearch/data
    ports:
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.6
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  db:
    driver: local
  esdata:
    driver: local
  esdatatest:
    driver: local